CREATE TABLE tasks (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    progress BIGINT NOT NULL,
    "target" BIGINT NOT NULL,
    "status" VARCHAR(255) NOT NULL
);

INSERT INTO tasks ("name", progress, "target", "status") VALUES
('Task 1', 0, 30, 'PENDING'),
('Task 2', 0, 30, 'PENDING'),
('Task 3', 0, 15, 'PENDING'),
('Task 4', 0, 40, 'PENDING'),
('Task 5', 0, 25, 'PENDING'),
('Task 6', 0, 30, 'PENDING'),
('Task 7', 0, 30, 'PENDING'),
('Task 8', 0, 15, 'PENDING'),
('Task 9', 0, 40, 'PENDING'),
('Task 10', 0, 25, 'PENDING'),
('Task 11', 0, 30, 'PENDING'),
('Task 12', 0, 30, 'PENDING'),
('Task 13', 0, 15, 'PENDING'),
('Task 14', 0, 40, 'PENDING'),
('Task 15', 0, 25, 'PENDING');