DROP TABLE IF EXISTS tasks;

CREATE TABLE tasks (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    progress INT NOT NULL,
    "target" INT NOT NULL,
    "status" VARCHAR(255) NOT NULL,
    error_rate INT NOT NULL
);

INSERT INTO tasks (progress, "target", "status", error_rate) VALUES
(0, 30, 'PENDING', 20),
(0, 45, 'PENDING', 15),
(0, 35, 'PENDING', 10),
(0, 20, 'PENDING', 5),
(0, 25, 'PENDING', 25),
(0, 15, 'PENDING', 15),
(0, 20, 'PENDING', 20),
(0, 30, 'PENDING', 10),
(0, 35, 'PENDING', 15),
(0, 40, 'PENDING', 25),
(0, 35, 'PENDING', 20),
(0, 45, 'PENDING', 10),
(0, 40, 'PENDING', 25),
(0, 40, 'PENDING', 15),
(0, 25, 'PENDING', 20),
(0, 30, 'PENDING', 25),
(0, 35, 'PENDING', 10),
(0, 35, 'PENDING', 15),
(0, 40, 'PENDING', 5),
(0, 20, 'PENDING', 5);

SELECT * FROM tasks;